name: xtensor-io
channels:
  - conda-forge
dependencies:
  - xtensor-io=0.10.3
  - xeus-cling=0.10.0
  - xwidgets=0.24.0
  - ffmpeg=3.4.2  # openimageio is being added as a runtime requirement to xtensor-io
  - widgetsnbextension
