name: xtensor-io
channels:
  - QuantStack
  - conda-forge
dependencies:
  - xtensor
  - boost ==1.66.0
  - boost-cpp ==1.66.0
  - widgetsnbextension
  - xtensor-io ==0.5.0
  - xeus-cling ==0.4.5
  - xwidgets ==0.12.2
  - openimageio ==1.8.9
  - notebook
