name: xtensor-io
channels:
  - QuantStack
  - conda-forge
dependencies:
  - xtensor
  - widgetsnbextension
  - xtensor-io ==0.7.0
  - xeus-cling ==0.4.9
  - xwidgets ==0.15.0
  - openimageio ==1.8.9
  - notebook
