name: xtensor-io
channels:
  - QuantStack
  - conda-forge
dependencies:
  - xtensor
  - boost ==1.66.0
  - boost-cpp ==1.66.0
  - widgetsnbextension
  - xtensor-io ==0.3.0
  - xeus-cling ==0.4.2
  - xwidgets ==0.10.0
  - notebook
