parameters:
  - name: 'platform'
    type: string

steps:
  - script: |
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda env create --file environment-dev.yml
    displayName: Install dependencies

  - script: |
      source activate xtensor-io
      conda install gxx_linux-64 libgcc -c conda-forge
    condition: eq('${{ parameters.platform }}', 'Linux')
    displayName: Install conda-forge compilers

  - script: |
      source activate xtensor-io
      export LDFLAGS="${LDFLAGS} -Wl,-rpath,$CONDA_PREFIX/lib"
      export LINKFLAGS="${LDFLAGS}"
      mkdir build
      cd build
      cmake -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DDOWNLOAD_GTEST=ON -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX $(Build.SourcesDirectory)
    displayName: Configure xtensor-io
    workingDirectory: $(Build.BinariesDirectory)

  - script: |
      source activate xtensor-io
      make -j2 test_xtensor_io_lib
      make -j2 test_xtensor_io_ho
    displayName: Build xtensor-io
    workingDirectory: $(Build.BinariesDirectory)/build

  - script: |
      source activate xtensor-io
      ./test_xtensor_io_lib
      ./test_xtensor_io_ho
    displayName: Test xtensor-io
    workingDirectory: $(Build.BinariesDirectory)/build/test

